name: Create Release Branch
on:
  push: 
  pull_request:
  release: 
    types:
      - created
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: probando
      if: github.event_name == 'release' && github.event.action == 'created'
      run: echo "release"
