name: Create Release Branch
on:
  release:
    types: [created]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event_name }}
        run: echo $MESSAGE